online/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('', views.index , name='index'),
    path('contact/',views.contact, name='contact'),
    path('signup/', views.signup , name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name = 'core/login.html' , authentication_form = LoginForm) , name='login')
    # using the django login defualt 
]

online/deshboard/urls.py
from django.urls import path
from . import views
app_name = 'deshboard'
urlpatterns = [
    path('', views.index , name='index'),
]

online/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items , name='items'),
    path('new/', views.new , name='new'),
    path('<int:pk>/', views.detail ,name='detail'),
    path('<int:pk>/delete', views.delete ,name='delete'),
    path('<int:pk>/edit', views.edit ,name='edit'),
]

online/online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from core.views import contact, index

urlpatterns = [
    
    path('', include('core.urls')),
    path('deshboard/', include('deshboard.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
] 


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

online/core/models.py
from django.db import models

# Create your models here.

online/deshboard/models.py
from django.db import models

# Create your models here.

online/item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    

class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category,related_name='items', on_delete=models.CASCADE)
    description = models.TextField(blank=True , null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User ,  related_name='items', on_delete=models.CASCADE)
    price = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='image_fiel' , blank=True , null= True )
    
    
    
    def __str__(self):
        return self.name
    

online/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'your username'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'your username'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username' , 'email' , 'password1', 'password2')
        



            

online/item/forms.py
from django import forms

from . models import Item

class NewForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')
        
        
        


class EditForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ( 'name', 'description', 'price', 'image', 'is_sold')

online/core/views.py
# the core app, contains the views to the home page that's all that needs to be send to the template homepage
# 

from django.shortcuts import redirect, render
from item.models import *
from core.forms import SignupForm
# Create your views here.
# the veiws desplaye information to the home page that's any information to be displayer to the home page
def index(request):
    items = Item.objects.filter(is_sold = False)
    
    category = Category.objects.all()
    
    context = {
        'items':items,
        'category':category
    }
    
    return render(request , 'core/index.html', context)


def contact(request):
    
    return render(request , 'core/contact.html')


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    
    return render(request , 'core/signup.html', {'form':form,})

online/deshboard/views.py
from django.shortcuts import render , redirect , get_list_or_404

from django.contrib.auth.decorators import login_required
from item.models import Item



@login_required
def index(request):
    items = Item.objects.filter(created_by = request.user)
    
    
    return render(request , 'deshboard/index.html', {'items':items})

online/item/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from item.forms import EditForm, NewForm
from django.contrib.auth.decorators import login_required
from item.models import Category, Item
from django.db.models import Q
# Create your views here.

# contains the information about the dettails page 
def items(request):
    query = request.GET.get('query')
    categor_id = request.GET.get('categor',0)
    
    items= Item.objects.filter(is_sold = False)
    category = Category.objects.all()
    if query:
        items= items.filter(Q(name__icontains = query)| Q(description__icontains = query))
    
    return render(request , 'item/items.html', {'items':items, 'query':query, 'category':category,'categor_id':int(categor_id)})




def detail(request , pk): # each item has a pk value 
    item = get_object_or_404(Item, pk=pk) # the Item meqans we are taking data from the models of the item app
    relate_item = Item.objects.filter(category = item.category , is_sold = False).exclude(pk = pk)[0:3]
    
    context = {
        'item':item,
        'relate_item':relate_item
    }
    
    return render(request , 'item/detail.html', context)




@login_required
def new(request):
    if request.method == "POST":
        form = NewForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk = item.id)
    else:
        form = NewForm()
    return render(request ,'item/form.html', {'form':form,'title':'New item'})




@login_required
def edit(request ,pk):
    item =get_object_or_404(Item, pk = pk , created_by = request.user)
    if request.method == "POST":
        form = EditForm(request.POST, request.FILES,instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk = item.id)
    else:
        form = EditForm(instance=item)
    return render(request ,'item/form.html', {'form':form,'title':'Edit item'})










@login_required
def delete(request , pk ):
    pk = int(pk)
    item =get_object_or_404(Item, pk=pk , created_by = request.user)
    item.delete()
    return redirect('deshboard:index')

online/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title  %}{% endblock %} | My site</title>
</head>
 <body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200" >
        <a href="/" class="text-xl font-semibold" >Pubble</a>
        <div class="space-x-6">

            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a><br>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browser</a><br>
              {% if request.user.is_authenticated %}
             <strong>Welcome {{user.username}} <br></strong>
             <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" >Inbox</a>
             <a href="{% url 'deshboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700" >Desboard</a>
               
              {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" >Sign Up</a>
            <a href="{% url 'core:login'  %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700" >Login</a>
              {% endif %}
        </div>
    </nav>
    <div class=" px-6 py-6">
         {% block content %}

          {% endblock %}      
    </div>
    <footer class="py-6 px-6 flex justify-between  bg-gray-800" >
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400" >About</h3>

            <p class="text-lg text-gray-500" > Famer's house a place to be in the future if you love and keep our policies you will love the place. Thank's for using our platform </p>
        </div>
    </footer>
 </body>
</html>

online/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Welcome {% endblock %}

{% block content  %}


{% endblock %}

online/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome {% endblock %}

{% block content  %}
  
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl" >
    <h2 class="mb-12 text-2xl text-center" >Newest Items</h2>

    <div class="grid grid-colo-3 gap-3">
       {% for item in items %}
       <div >

        <a href="{% url 'item:detail' item.id  %}">
            <div>
                <img src="{{ item.image.url  }}" class="rounded-t-xl ">
            </div>

            <div class="p-6 bg-white rounded-b-xl" >

                <h2 class="text-2xl" >{{item.name}}</h2>
                 <p > Price : {{item.price}} CFA</p>
            </div>
        </a>

       </div>
   
     {% endfor %}
    </div>
      
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl" >
    <h2 class="mb-12 text-2xl text-center" >Categories</h2>

    <div class="grid grid-colo-3 gap-3">
      {% for catego in category %}

      <a href="#">
     

        <div class="p-6 bg-white rounded-b-xl" >

            <h2 class="text-2xl" >{{catego.name}}   {{catego.items.count}}</h2>
        </div>
    </a>
    </div>
    {% endfor %}
</div> 

{% endblock %}

online/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content  %}

<div class="dropdown-menu">
    <form  method="post" action="">
        {% csrf_token %}
      
      

        <div class="form-group">
            <label for="exampleDropdownFormEmail2">Username</label><br>
           {{form.username}}
          </div>
          


          <div class="form-group">
            <label for="exampleDropdownFormEmail2">Password</label><br>
            {{form.password}}
          </div>


         

        {% if form.errors or form.non_field_errors %}

        <div>
            {% for field in form %}

            {{field.errors}}

            {% endfor %}
            {{form.non_fields_errors}}

        </div>

        {% endif %}
                        
    <button type="submit" >Submit</button>
    </form>
   
  </div>






{% endblock %}

online/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign Up {% endblock %}

{% block content  %}

<div class="dropdown-menu">
    <form  method="post" action="">
        {% csrf_token %}
      
      

        <div class="form-group">
            <label for="exampleDropdownFormEmail2">Username</label><br>
           {{form.username}}
          </div>
          <div class="form-group">
            <label for="exampleDropdownFormEmail2">Email address</label><br>
            {{form.email}}
          </div>


          <div class="form-group">
            <label for="exampleDropdownFormEmail2">Password</label><br>
            {{form.password1}}
          </div>


          <div class="form-group">
            <label for="exampleDropdownFormEmail2"> Repeat Password</label><br>
            {{form.password2}}
          </div>

        {% if form.errors or form.non_field_errors %}

        <div>
            {% for field in form %}

            {{field.errors}}

            {% endfor %}
            {{form.non_fields_errors}}

        </div>

        {% endif %}
                        
    <button type="submit" >Submit</button>
    </form>
   
  </div>






{% endblock %}

online/deshboard/templates/deshboard/index.html
{% extends 'core/base.html' %}

{% block title %}Deshboard{% endblock %}

{% block content  %}
  
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl" >
    <h2 class="mb-12 text-2xl text-center" >My Items</h2>

    <div class="grid grid-colo-3 gap-3">
       {% for item in items %}
       <div >

        <a href="{% url 'item:detail' item.id  %}">
            <div>
                <img src="{{ item.image.url  }}" class="rounded-t-xl ">
            </div>

            <div class="p-6 bg-white rounded-b-xl" >

                <h2 class="text-2xl" >{{item.name}}</h2>
                 <p > Price : {{item.price}} CFA</p>
            </div>
        </a>

       </div>
   
     {% endfor %}
    </div>
</div>

{% endblock %}

online/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{item.name}}{% endblock %}

{% block content  %}



<div>
    <div class="col-span-3">

        <img src="{{item.image.url}}" class="rounded-xl">
                            
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>

        <p class="text-gray-500"> <strong> Price {{ item.price }} CFA </strong>  </p>
        <p> <strong>Owner: {{ item.created_by}}</strong>  </p>
            {% if item.description %}
        <p> <strong>infor : {{item.description}}  </strong> </p>
          {% endif %}
            
        {% if request.user == item.created_by %}     
        <div>
            <p>This is your item!</p>
            <button style="position: bg-primary;" ><a href="{% url 'item:delete' item.id %}">Delete</a></button>
        </div>
        <div>
            
            <button style="position: bg-primary;" ><a href="{% url 'item:edit' item.id %}">Edit</a></button>
        </div>
         
        {% else %}

       <button> <a href="#">
        <button  style="background-color: aqua;" >Contact seller</button>
    </a></button>
        {% endif %}
    </div>
</div>


<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl" >
    <h2 style="background-color: cornflowerblue;" >Relate Items</h2>

    <div class="grid grid-colo-3 gap-3">
       {% for item in  relate_item   %}
       <div >

        <a href="{% url 'item:detail' item.id  %}">
            <div>
                <img src="{{ item.image.url  }}" class="rounded-t-xl ">
            </div>

            <div class="p-6 bg-white rounded-b-xl" >

                <h2 class="text-2xl" >{{item.name}}</h2>
                 <p > Price : {{item.price}} CFA</p>
            </div>
        </a>

       </div>
   
     {% endfor %}
    </div>














{% endblock %}

online/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %} {{title}} {% endblock %}

{% block content  %}

<div class="dropdown-menu">
    <form  method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
      
      

        <div class="form-group">
            <label for="exampleDropdownFormEmail2">Category</label><br>
           {{form.category}}
          </div>
          <div class="form-group">
            <label for="exampleDropdownFormEmail2">Name</label><br>
            {{form.name}}
          </div>


          <div class="form-group">
            <label for="exampleDropdownFormEmail2">Description</label><br>
            {{form.description}}
          </div>


          <div class="form-group">
            <label for="exampleDropdownFormEmail2">Price</label><br>
            {{form.price}}
          </div>


          <div class="form-group">
            <label for="exampleDropdownFormEmail2">Image</label><br>
            {{form.image}}
          </div>

       
                        
    <button type="submit" >Submit</button>
    </form>
   
  </div>






{% endblock %}

online/item/templates/items.html
{% extends 'core/base.html' %}

{% block title %}Seach{% endblock %}

{% block content  %}


<div>

     <div>
        <form action="get" action="{% url 'item:items' %}">

            <input type="text" name="query" id="" value="query">

            <button>Search</button>
              

        </form>
        <hr>
        <p>categories</p>
    
        <ul>
            {% for categor in category %}
            <li class="{% if categor.id == categor_id %} {% endif %}">
                <a href="{% url 'item:items' %}?query={{query}}&categor={{categor.id}} ">{{categor.name}}</a>
            </li>
            {% endfor %}
        </ul>
      
     </div>
     

    <div class="grid grid-colo-3 gap-3">
        {% for item in items %}
        <div >
 
         <a href="{% url 'item:detail' item.id  %}">
             <div>
                 <img src="{{ item.image.url  }}" class="rounded-t-xl ">
             </div>
 
             <div class="p-6 bg-white rounded-b-xl" >
 
                 <h2 class="text-2xl" >{{item.name}}</h2>
                  <p > Price : {{item.price}} CFA</p>
             </div>
         </a>
 
        </div>
    
      {% endfor %}
     
     </div>
</div>


{% endblock %}